version: '3.8'
services:
#  postgres-db:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mhaddaou
      - POSTGRES_USER=mhaddaou
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db